# Generated by Django 3.2.17 on 2023-02-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('contact', models.CharField(max_length=200)),
                ('commission_rate', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyNo', models.CharField(max_length=90)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.BigIntegerField()),
                ('commission', models.BigIntegerField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.agent')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=90)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.policy')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.user'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.agent')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.agent')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.login'),
        ),
    ]
