# Generated by Django 3.2.17 on 2023-02-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0003_remove_agent_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='uid',
        ),
    ]
