# Generated by Django 3.2.17 on 2023-02-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0004_remove_policy_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='aid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='lapp.agent'),
            preserve_default=False,
        ),
    ]
